version: "3.8"

services:
  app:
    image: lexforor/lab
    command: npm run start
    ports:
      - 3000:3000
      - 8080:8080
    working_dir: /home/Lab
    volumes:
      - ./:/lab
    environment:
      NODE_ENV: dev
      DEV_APP_PORT: 3000
      TTL_DELAY: 30000
      QUEUE_HOST: redis
      STORAGE_HOST: db
      TOKEN_KEY: EDABF42E713D54D6E24CECB25527F
    depends_on: [db,redis]
  db:
    image: mysql:8.0
    restart: always
    volumes:
      - todo-mysql-data:/var/lib/mysql
    environment:
      - MYSQL_USER=root
      - MYSQL_PASSWORD=Timafifa14
      - MYSQL_ROOT_PASSWORD=Timafifa14
      - MYSQL_DATABASE=lab
  redis:
    image: redis:6.2
    restart: always
volumes:
  todo-mysql-data:
